### ISSUE TITLE
'This error originates from a subprocess, and is likely not a problem with pip'

### ISSUE THREAD

**Issue by Suyeonnie** [deepakpadhi986/AI-Resume-Analyzer#2]
hi,
i tried to clone your project AI-Resume-Analyzer. Unfortunately an error occured while installing requirements.txt

`Traceback (most recent call last):
        File "D:\AI-Resume-Analyzer\venvapp\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\AI-Resume-Analyzer\venvapp\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "D:\AI-Resume-Analyzer\venvapp\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\suyeon\AppData\Local\Temp\pip-build-env-14xqsx9t\overlay\Lib\site-packages\setuptools\build_meta.py", line 355, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\suyeon\AppData\Local\Temp\pip-build-env-14xqsx9t\overlay\Lib\site-packages\setuptools\build_meta.py", line 325, in _get_build_requires
          self.run_setup()
        File "C:\Users\suyeon\AppData\Local\Temp\pip-build-env-14xqsx9t\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in run_setup
          exec(code, locals())
        File "<string>", line 256, in <module>
        File "<string>", line 195, in setup_package
        File "C:\Users\suyeon\AppData\Local\Temp\pip-build-env-14xqsx9t\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1154, in cythonize
          cythonize_one(*args)
        File "C:\Users\suyeon\AppData\Local\Temp\pip-build-env-14xqsx9t\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 1321, in cythonize_one
          raise CompileError(None, pyx_file)
      Cython.Compiler.Errors.CompileError: thinc/extra/eg.pyx
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.`

I don't know if my settings are problem.
Could you possibly help me with this problem?

**Comment by deepakpadhi986** [comment]
### Make sure you have this requirements on your machine
1. You Need to install [Visual Build tools](https://aka.ms/vs/17/release/vs_BuildTools.exe) and in installer select desktop development with C++
2. You have [python 3.9.12](https://www.python.org/downloads/release/python-3912/)

Then redo the installation steps from start it will work if not, issues are welcome 😊
